import { CampData } from './types';
import { getAssetUrl } from './utils/assetUrl';

export const campData: CampData = {
  name: 'ما وراء المحتوى',
  project: 'الحقيقة تهمنا: بناء شبكة شبابية لمواجهة التضليل وخطاب الكراهية',
  description: 'ينفذ المخيم التدريبي «ما وراء المحتوى» ضمن مشروع «الحقيقة تهمنا: بناء شبكة شبابية لمواجهة التضليل وخطاب الكراهية» بتنفيذ من «تيقن» ودعم من الوكالة الفرنسية للتعاون الإعلامي CFI.',
  date: '10 — 12 أيلول/سبتمبر 2026',
  programPdf: getAssetUrl('downloads/camp-training-program-v7.pdf'),
  trainers: [
    {
      id: 'trainer-0',
      name: 'أنس حواري',
      bio: 'صحفي ومدقق معلومات منذ 9 سنوات ومدرب في مجال تدقيق المعلومات وكتابة المحتوى، مؤسس منصة تيقن لتدقيق المعلومات.',
      specialty: 'تدقيق المعلومات وكتابة المحتوى',
      icon: 'Mic',
      image: getAssetUrl('trainers/optimized/anas-hawari.webp'),
      initials: 'أ ح',
    },
    {
      id: 'trainer-1',
      name: 'أمير أبو عرام',
      bio: 'مدرب وميسّر في تحقيقات المصادر المفتوحة، يقود جلسة OSINT ويسهم في تهيئة المشاركين وبناء بيئة تعلم تشاركية.',
      specialty: 'تحقيقات المصادر المفتوحة',
      icon: 'Network',
      image: getAssetUrl('trainers/optimized/amir-abu-arram.webp'),
      initials: 'أ أ',
    },
    {
      id: 'trainer-2',
      name: 'د. رائد نعيرات',
      bio: 'أكاديمي وباحث متخصص في العلوم السياسية وتحليل السياسات العامة وإدارة الصراعات. يمتلك خبرة تدريبية في التحليل السياسي والاستراتيجي وإعداد السياسات والأوراق البحثية وإدارة الأزمات، وله حضور إعلامي في تحليل القضية الفلسطينية والتطورات الإقليمية والدولية.',
      specialty: 'التحليل السياسي',
      icon: 'FileSearch',
      image: getAssetUrl('trainers/optimized/raed-nueirat.webp'),
      initials: 'ر ن',
    },
    {
      id: 'trainer-3',
      name: 'وطن نعيرات',
      bio: 'مدققة معلومات بخبرة تتجاوز أربع سنوات، ومدققة معتمدة في «تشات بوت» الشبكة العربية لمدققي المعلومات، ومدربة في مجال تدقيق المعلومات والتحقق الرقمي.',
      specialty: 'تدقيق المعلومات والتحقق الرقمي',
      icon: 'SearchCheck',
      image: getAssetUrl('trainers/optimized/watan-nueirat.webp'),
      initials: 'و ن',
    },
    {
      id: 'trainer-4',
      name: 'مخلص سمارة',
      bio: 'مدرب في المجالين التربوي والإعلامي، ومختص في الشأن الاجتماعي، يعمل في الإعلام منذ قرابة عشرين عامًا، وناشط ومتحدث في القضايا التربوية والاجتماعية.',
      specialty: 'أخلاقيات الذكاء الاصطناعي',
      icon: 'Brain',
      image: getAssetUrl('trainers/optimized/mokhles-samara.webp'),
      initials: 'م س',
    },
    {
      id: 'trainer-5',
      name: 'إبراهيم الرنتيسي',
      bio: 'مراسل صحفي تلفزيوني بخبرة تتجاوز 18 عامًا، ومعد ومقدم برامج ومواد وثائقية. يمتلك خبرة في المونتاج والتصوير وصحافة الموبايل وتوظيف الذكاء الاصطناعي في العمل الصحفي.',
      specialty: 'الفيديو والقصص الرقمية',
      icon: 'Clapperboard',
      image: getAssetUrl('trainers/optimized/ibrahim-rantisi.webp'),
      initials: 'إ ا',
    },
  ],
  days: [
    {
      id: 'day-0',
      label: 'اليوم الأول',
      date: 'الخميس 10 أيلول/سبتمبر',
      title: 'التحقق من المعلومات في بيئة اللايقين',
      sessions: [
        {
          id: 'd0-s0',
          time: '12:00–12:15',
          duration: '١٥ دقيقة',
          category: 'workshop',
          categoryLabel: 'افتتاح وتوجيه',
          shortWord: 'الافتتاح والترحيب',
          title: 'الافتتاح',
          trainerId: 'trainer-0',
          trainerLabel: 'أنس حواري',
          description: 'الترحيب بالمشاركين، تقديم المشروع والمخيم، واستعراض الأهداف العامة ومسار الأيام الثلاثة.',
          tags: ['افتتاح', 'أهداف المخيم', 'تيقن'],
          keyTopics: [
            'الترحيب والتعريف بفريق ومشروع «الحقيقة تهمنا»',
            'خارطة الطريق للأيام الثلاثة والنتائج المتوقعة',
            'قواعد العمل التشاركي والمجموعات التدريبية'
          ],
          icon: 'Mic',
          isBreak: false,
        },
        {
          id: 'd0-revised-1',
          time: '12:15–2:15',
          duration: 'ساعتان',
          category: 'panel',
          categoryLabel: 'جلسة حوارية',
          shortWord: 'جلسة حوارية',
          icon: 'Mic',
          title: 'جلسة حوارية',
          description: 'مستقبل الصحافة، التحقق من المعلومات، وتحديات التضليل الرقمي',
          trainerId: null,
          trainerLabel: 'إعلاميون فلسطينيون',
          tags: ['صحافة', 'حوار', 'مكافحة التضليل', 'نقاش مفتوح'],
          keyTopics: [
            'واقع الصحافة الفلسطينية في ظل تدفق المعلومات المتسارع',
            'آليات مواجهة السرديات المضللة وخطاب الكراهية',
            'حوار تفاعلي مفتوح بين المشاركين ونخبة من الإعلاميين'
          ],
          isBreak: false,
          isPanel: true,
        },
        {
          id: 'd0-s2-break',
          time: '2:15–3:00',
          duration: '٤٥ دقيقة',
          category: 'break',
          categoryLabel: 'استراحة غداء',
          shortWord: 'استراحة غداء',
          title: 'استراحة غداء',
          trainerId: null,
          trainerLabel: null,
          description: 'استراحة غداء وتواصل تشاركي بين المشاركين والمدربين.',
          tags: ['استراحة', 'غداء', 'تواصل'],
          icon: 'Utensils',
          isBreak: true,
        },
        {
          id: 'd0-s4',
          time: '3:00–4:30',
          duration: 'ساعة ونصف',
          category: 'workshop',
          categoryLabel: 'تدريب تطبيقي',
          shortWord: 'تدقيق المعلومات',
          title: 'مقدمة حول تدقيق المعلومات',
          trainerId: 'trainer-3',
          trainerLabel: 'وطن نعيرات',
          description: 'مبادئ تدقيق المعلومات، تقييم المصادر، تتبع الادعاءات، وبناء مسار تحقق واضح.',
          tags: ['تدقيق المعلومات', 'تقييم المصادر', 'مسار التحقق'],
          keyTopics: [
            'معايير التحقق الصارمة ومنهجية تيقن المعتمدة',
            'تتبع مصادر الادعاءات وفحص التوثيق الأولي',
            'تمارين عملية على كشف التضليل المنتشر'
          ],
          icon: 'SearchCheck',
          isBreak: false,
        },
        {
          id: 'd0-s5',
          time: '4:30–5:30',
          duration: 'ساعة كاملة',
          category: 'workshop',
          categoryLabel: 'تطبيق عملي OSINT',
          shortWord: 'تحديد الموقع',
          title: 'تحديد الموقع الجغرافي (Geolocation)',
          trainerId: 'trainer-3',
          trainerLabel: 'وطن نعيرات',
          description: 'توظيف الأدلة البصرية والخرائط والمصادر المفتوحة لتحديد مواقع الصور ومقاطع الفيديو بدقة.',
          tags: ['Geolocation', 'خرائط', 'أدلة بصرية', 'OSINT'],
          keyTopics: [
            'استخدام صور الأقمار الصناعية وخرائط جوجل والظلال',
            'مطابقة المعالم الطبوغرافية والشواهد المعمارية',
            'تحديد مواقع تسجيل مقاطع فيديو ميدانية ملتبسة'
          ],
          icon: 'MapPin',
          isBreak: false,
        },
        {
          id: 'd0-s5-break',
          time: '5:30–6:45',
          duration: 'ساعة وربع',
          category: 'break',
          categoryLabel: 'استراحة',
          shortWord: 'استراحة ونشاط',
          title: 'استراحة واستعادة نشاط',
          trainerId: null,
          trainerLabel: null,
          description: 'استراحة قصيرة ومشروبات وتجهيز للجلسة المسائية.',
          tags: ['استراحة', 'تواصل'],
          icon: 'Coffee',
          isBreak: true,
        },
        {
          id: 'd0-s2',
          time: '6:45–7:15',
          duration: '٣٠ دقيقة',
          category: 'lecture',
          categoryLabel: 'تحليل سياسي',
          shortWord: 'الخبر السياسي',
          title: 'الخبر السياسي في حالة اللايقين',
          trainerId: 'trainer-2',
          trainerLabel: 'د. رائد نعيرات',
          description: 'فهم صناعة الخبر السياسي عند نقص المعلومات، وتحليل السياق والمصادر وتحديات التحقق قبل النشر.',
          tags: ['تحليل سياسي', 'اللايقين', 'الأزمات', 'سياق إخباري'],
          keyTopics: [
            'سيكولوجيا نشر الأخبار أثناء الأزمات والتوترات',
            'قراءة ما وراء التصريحات الرسمية ومؤشرات التسريب',
            'كيف يحمي الصحفي نفسه من السقوط في فخ التضليل السياسي'
          ],
          icon: 'FileSearch',
          isBreak: false,
        },
      ],
    },
    {
      id: 'day-1',
      label: 'اليوم الثاني',
      date: 'الجمعة 11 أيلول/سبتمبر',
      title: 'المصادر المفتوحة والذكاء الاصطناعي والحقوق الرقمية',
      sessions: [
        {
          id: 'd1-s0',
          time: '9:30–12:15',
          duration: 'ساعتان و٤٥ دقيقة',
          category: 'workshop',
          categoryLabel: 'تحقيقات استقصائية',
          shortWord: 'تحقيقات OSINT',
          title: 'تحقيقات المصادر المفتوحة',
          trainerId: 'trainer-1',
          trainerLabel: 'أمير أبو عرام',
          description: 'مقدمة تطبيقية في OSINT: جمع المعلومات من المصادر المفتوحة، التحقق منها، تنظيم الأدلة وبناء نتائج قابلة للتوثيق.',
          tags: ['OSINT', 'مصادر مفتوحة', 'أدلة رقمية', 'توثيق'],
          keyTopics: [
            'منهجية جمع البيانات الرقمية وتتبع الآثار الرقمية',
            'استخدام محركات البحث المتخصصة والأرشيف الرقمي',
            'بناء شجرة الأدلة والتحقق من صحة المقاطع المنتشرة'
          ],
          icon: 'Network',
          isBreak: false,
        },
        {
          id: 'd1-s1-break',
          time: '12:15–1:15',
          duration: 'ساعة كاملة',
          category: 'break',
          categoryLabel: 'استراحة',
          shortWord: 'استراحة شاي',
          title: 'استراحة',
          trainerId: null,
          trainerLabel: null,
          description: 'استراحة للمشاركين وتجهيز لأجهزة العمل.',
          tags: ['استراحة'],
          icon: 'Coffee',
          isBreak: true,
        },
        {
          id: 'd1-s2',
          time: '1:15–2:45',
          duration: 'ساعة ونصف',
          category: 'workshop',
          categoryLabel: 'أخلاقيات رقمية',
          shortWord: 'أخلاقيات AI',
          title: 'أخلاقيات الذكاء الاصطناعي',
          trainerId: 'trainer-4',
          trainerLabel: 'مخلص سمارة',
          description: 'المسؤولية المهنية، الخصوصية والتحيز، الشفافية والإفصاح، وحدود استخدام أدوات الذكاء الاصطناعي في الإعلام.',
          tags: ['ذكاء اصطناعي', 'أخلاقيات', 'خصوصية', 'تحيز'],
          keyTopics: [
            'المعايير الأخلاقية لاستخدام خوارزميات الذكاء الاصطناعي',
            'التحيز الخوارزمي وتأثيره على المحتوى العربي والفلسطيني',
            'الشفافية وحقوق الملكية الفكرية والإفصاح التحريري'
          ],
          icon: 'Brain',
          isBreak: false,
        },
        {
          id: 'd1-s3-break',
          time: '2:45–3:30',
          duration: '٤٥ دقيقة',
          category: 'break',
          categoryLabel: 'استراحة غداء',
          shortWord: 'استراحة غداء',
          title: 'استراحة غداء',
          trainerId: null,
          trainerLabel: null,
          description: 'وجبة غداء واستراحة للمشاركين.',
          tags: ['استراحة', 'غداء'],
          icon: 'Utensils',
          isBreak: true,
        },
        {
          id: 'd0-s6',
          time: '3:30–5:30',
          duration: 'ساعتان',
          category: 'workshop',
          categoryLabel: 'تدريب تطبيقي',
          shortWord: 'ما قبل النشر',
          title: 'تدقيق معلومات ما قبل النشر',
          trainerId: 'trainer-3',
          trainerLabel: 'وطن نعيرات',
          description: 'إجراءات التحقق التحريري قبل النشر، وتوثيق الأدلة وتقليل احتمالات الخطأ المهني.',
          tags: ['تحرير صحفي', 'ما قبل النشر', 'سلامة المحتوى'],
          keyTopics: [
            'قائمة التحقق الميداني للغرفة الإخبارية',
            'بروتوكولات فحص الأسماء والأرقام والاقتباسات',
            'تمارين عملية على تدقيق مواد صحفية قبل بثها'
          ],
          icon: 'SearchCheck',
          isBreak: false,
        },
        {
          id: 'd0-s8',
          time: '5:30–7:30',
          duration: 'ساعتان',
          category: 'lab',
          categoryLabel: 'مختبر ذكاء اصطناعي',
          shortWord: 'كشف تزييف AI',
          title: 'التحقق من المحتوى المولّد بالذكاء الاصطناعي',
          trainerId: 'trainer-3',
          trainerLabel: 'وطن نعيرات',
          description: 'مؤشرات اكتشاف المحتوى الاصطناعي، التحقق من الصور والفيديو، وتجنب الأحكام المبنية على أداة واحدة.',
          tags: ['تزييف عميق', 'توليد ذكاء اصطناعي', 'فحص الصور'],
          keyTopics: [
            'العلامات البصرية والملمسية الدالة على الصور المولدة',
            'أدوات فحص الميتاداتا وتدرجات الضوء والتشوهات',
            'منهجية عدم الاعتماد على كواشف AI التلقائية وفحص السياق'
          ],
          icon: 'SearchCheck',
          isBreak: false,
        },
      ],
    },
    {
      id: 'day-2',
      label: 'اليوم الثالث',
      date: 'السبت 12 أيلول/سبتمبر',
      title: 'توظيف تقنيات الذكاء الاصطناعي في إنتاج الفيديو والقصص الرقمية',
      sessions: [
        {
          id: 'd2-s0',
          time: '9:30–10:00',
          duration: '٣٠ دقيقة',
          category: 'workshop',
          categoryLabel: 'توجيه المجموعات',
          shortWord: 'مدخل وتمهيد',
          title: 'مدخل وتمهيد',
          trainerId: 'trainer-5',
          trainerLabel: 'إبراهيم الرنتيسي',
          description: 'عرض نماذج ملهمة، شرح مهمة اليوم، قياس التوقعات وتقسيم المشاركين إلى مجموعات عمل إبداعية.',
          tags: ['توجيه', 'فرق عمل', 'قصص رقمية'],
          keyTopics: [
            'استعراض أمثلة واقعية لقصص مصورة استندت للتحقق',
            'توزيع الأدوار داخل مجموعات الإنتاج',
            'شرح جدول الإنتاج المكثف لليوم الختامي'
          ],
          icon: 'Clapperboard',
          isBreak: false,
        },
        {
          id: 'd2-s1',
          time: '10:00–12:15',
          duration: 'ساعتان وربع',
          category: 'workshop',
          categoryLabel: 'كتابة وسيناريو',
          shortWord: 'كتابة السيناريو',
          title: 'من الفكرة إلى السيناريو',
          trainerId: 'trainer-5',
          trainerLabel: 'إبراهيم الرنتيسي',
          description: 'اختيار القضية والجمهور، تحديد الزاوية والرسالة، بناء الحبكة، وتوظيف الذكاء الاصطناعي في البحث وكتابة السيناريو والتعليق الصوتي مع المراجعة والتحقق.',
          tags: ['سيناريو', 'برومبت', 'حبكة درامية', 'تعليق صوتي'],
          keyTopics: [
            'هندسة أوامر التوليد (Prompts) لبناء نصوص صحفية موثقة',
            'تحديد الإيقاع الزمني للفيديو القصير (Reels / Shorts)',
            'صياغة نصوص التعليق الصوتي الجذابة مع الحفاظ على الدقة'
          ],
          icon: 'Clapperboard',
          isBreak: false,
        },
        {
          id: 'd2-s2-break',
          time: '12:15–1:15',
          duration: 'ساعة كاملة',
          category: 'break',
          categoryLabel: 'استراحة',
          shortWord: 'استراحة نصوص',
          title: 'استراحة ومراجعة النصوص',
          trainerId: null,
          trainerLabel: null,
          description: 'استراحة واستكمال مراجعة النصوص المقترحة بين الفرق والمدرب.',
          tags: ['استراحة'],
          icon: 'Coffee',
          isBreak: true,
        },
        {
          id: 'd2-s3',
          time: '1:15–2:45',
          duration: 'ساعة ونصف',
          category: 'workshop',
          categoryLabel: 'تصور بصري وستوري بورد',
          shortWord: 'الستوري بورد',
          title: 'من السيناريو إلى التصور البصري',
          trainerId: 'trainer-5',
          trainerLabel: 'إبراهيم الرنتيسي',
          description: 'تفكيك السيناريو إلى مشاهد، إعداد قائمة اللقطات والستوري بورد، تحديد أحجام اللقطات وحركات الكاميرا، وكتابة أوامر التوليد وتثبيت الأسلوب البصري.',
          tags: ['ستوري بورد', 'توليد بصري', 'لقطات سينمائية'],
          keyTopics: [
            'تحويل النص إلى جدول لقطات دقيق (Shot List)',
            'تثبيت ملامح الشخصيات والبيئة البصرية عبر أدوات التوليد',
            'التوافق البصري وتفادي التناقضات بين المشاهد'
          ],
          icon: 'Clapperboard',
          isBreak: false,
        },
        {
          id: 'd2-s4-break',
          time: '2:45–3:30',
          duration: '٤٥ دقيقة',
          category: 'break',
          categoryLabel: 'استراحة غداء',
          shortWord: 'استراحة غداء',
          title: 'استراحة غداء',
          trainerId: null,
          trainerLabel: null,
          description: 'استراحة غداء وتجميع المواد البصرية.',
          tags: ['استراحة', 'غداء'],
          icon: 'Utensils',
          isBreak: true,
        },
        {
          id: 'd2-s5',
          time: '3:30–5:30',
          duration: 'ساعتان',
          category: 'lab',
          categoryLabel: 'مختبر إنتاج تطبيقي',
          shortWord: 'مختبر الإنتاج',
          title: 'مختبر الإنتاج التطبيقي',
          trainerId: 'trainer-5',
          trainerLabel: 'إبراهيم الرنتيسي',
          description: 'توليد الصور والمشاهد وتحريكها، إنتاج التعليق الصوتي، إضافة الموسيقى والمؤثرات، وتنفيذ المونتاج وبناء النسخة الأولية.',
          tags: ['مونتاج', 'تحريك المشاهد', 'مؤثرات صوتية', 'إنتاج رقمي'],
          keyTopics: [
            'أدوات تحريك المشاهد الثابتة بالذكاء الاصطناعي',
            'توليد الصوت الاحترافي وتوافق الإلقاء مع المشاهد',
            'التوليف والمونتاج النهائي وإخراج الفيديو للنشر'
          ],
          icon: 'Clapperboard',
          isBreak: false,
        },
        {
          id: 'd2-s6',
          time: '5:30–6:00',
          duration: '٣٠ دقيقة',
          category: 'panel',
          categoryLabel: 'عرض وتقييم ختامي',
          shortWord: 'العرض والتقييم',
          title: 'العرض والتقييم',
          trainerId: 'trainer-5',
          trainerLabel: 'إبراهيم الرنتيسي',
          description: 'عرض إنتاج المجموعات، تقديم ملاحظات عملية، مناقشة الأخطاء، واستخلاص قواعد تحسين القصة الرقمية.',
          tags: ['عرض ختامي', 'تقييم', 'تغذية راجعة', 'توزيع شهادات'],
          keyTopics: [
            'عرض نتاج مقاطع الفيديو التي أنتجتها فرق المشاركين',
            'جلسة نقد بناء وتقييم مهني للمحتوى والتحقق والإخراج',
            'استخلاص التوصيات وتتويج أعمال المخيم'
          ],
          icon: 'Clapperboard',
          isBreak: false,
        },
      ],
    },
  ],
};
